name: 'Gitflow Finish Feature'
description: 'GitHub Action to complete a release based off of the gitflow workflow.'
branding:
  icon: git-merge
  color: white
inputs:
  pr-num:
    description:
      'The number of the pull request to finish.'
    required: true
  token:
    description:
      'Authentication token to allow the action to execute.'
    required: true
  repo-name:
    description:
      'The full name of the containing repository in the form owner/repo.'
    required: true
  merge-into-dev:
    description:
      'Sets whether to merge the release branch back into the development branch automatically.'
    required: false
    default: 'false'
  dev-branch-name:
    description:
      'The name of the development branch to merge the release branch into.'
    required: false
    default: 'develop'
  del-rel-branch:
    description:
      'Indicates whether to delete the release branch after completing all gitflow actions.'
    required: true
    default: 'true'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '--pr-num'
  - ${{ inputs.pr-num }}
  - '--token'
  - ${{ inputs.token }}
  - '--repo-name'
  - ${{ inputs.repo-name }}
  - '--merge-into-dev'
  - ${{ inputs.merge-into-dev }}
  - '--dev-branch-name'
  - ${{ inputs.dev-branch-name }}
  - '--del-rel-branch'
  - ${{ inputs.del-rel-branch }}